# Generated by Django 4.1.7 on 2023-03-13 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0002_alter_customer_country'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vehicle',
            old_name='vehicle_type',
            new_name='type',
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='real_cost',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='vehiclesize',
            name='name',
            field=models.CharField(choices=[('S', 'Small'), ('M', 'Medium'), ('L', 'Large')], max_length=2),
        ),
        migrations.AlterField(
            model_name='vehicletype',
            name='name',
            field=models.CharField(choices=[('C', 'City'), ('D', 'Dirt'), ('El', 'Electric')], max_length=2),
        ),
    ]
