# Generated by Django 4.1.7 on 2023-03-13 09:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("bike", "0005_alter_customer_address_alter_customer_city_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="RentalRate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("daily_rate", models.DecimalField(decimal_places=2, max_digits=5)),
                (
                    "vehicle_size",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="bike.vehiclesize",
                    ),
                ),
                (
                    "vehicle_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="bike.vehicletype",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Rental",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("rental_date", models.DateTimeField(auto_now_add=True)),
                ("return_date", models.DateTimeField(auto_now=True, null=True)),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="bike.customer"
                    ),
                ),
                (
                    "vehicle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="bike.vehicle"
                    ),
                ),
            ],
        ),
    ]
