# Generated by Django 4.1.7 on 2023-03-13 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bike", "0006_rentalrate_rental"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rental",
            name="return_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
